tryber/sd-013-b-project-trivia-react-redux

- README.md
- src/App.js
- src/components/InputCard.js
- src/index.js
- src/pages/Login.js
- src/redux/reducers/index.js
- src/redux/store/index.js
**Requisitos do projeto**
**Tela de início/login**
**Tela de jogo**
**Tela de feedback**
**Tela de ranking**
**Extra não avaliativo: Tela de configurações**
> [Grupo 18] - Project Trivia Redux

- package-lock.json
- package.json
- src/App.js
- src/index.js
- src/pages/Login.jsx
- src/reducers/index.js
- src/reducers/login.js
- src/reducers/trivia.js
- src/store/index.js
> Req1 pair programing

- package-lock.json
- package.json
- src/App.js
- src/components/EmailInput.jsx
- src/components/NameInput.jsx
- src/pages/Login.jsx
https://trello.com/c/bPlr7EOn/1-prioridade-0-tela-de-in%C3%ADcio-login-1-crie-a-tela-de-login-onde-a-pessoa-que-joga-deve-preencher-as-informa%C3%A7%C3%B5es-para-iniciar-um-jo
> [Group 11] - Requirement-01

- src/App.js
- src/actions/index.js
- src/pages/Game.jsx
- src/pages/Login.jsx
> :white_check_mark: Adicionando requisito 2

- package-lock.json
- package.json
- src/App.js
- src/Pages/Login.js
- src/Redux/Action/index.js
- src/Redux/Reducers/index.js
- src/Redux/Reducers/player.js
- src/Redux/Store/index.js
- src/index.js
> [Grupo 27] Project Trivia React Redux

- package-lock.json
- package.json
- src/App.js
- src/Components/EmailInput/index.js
- src/Components/LoginInput/index.js
- src/index.js
- src/pages/Login/index.js
- src/redux/actions/index.js
- src/redux/reducers/apiReducer.js
- src/redux/reducers/index.js
- src/redux/store/index.js
Primeiro commit para geração da branch
> [Grupo 8 - Joao França] Projeto trivia react-redux

- README.md
- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/index.js
- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/pages/Ranking.jsx
- src/redux/reducers/index.js
- src/redux/store/index.js
> [Grupo 7] - Iniciando projeto Trivia

- .github/workflows/main.yml
- README.md
- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/index.js
- src/pages/login.js
- src/redux/actions/index.js
- src/redux/reducers/index.js
- src/redux/reducers/user.js
- src/redux/store/index.js
> [Group 14] - Requisito 1

- package-lock.json
- package.json
- src/App.js
- src/actions/index.js
- src/index.js
- src/pages/FeedBack.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/pages/Ranking.jsx
- src/reducers/index.js
- src/store/index.js
https://trello.com/c/sEfaJUPM/1-prioridade-0-tela-de-in%C3%ADcio-login-1-crie-a-tela-de-login-onde-a-pessoa-que-joga-deve-preencher-as-informa%C3%A7%C3%B5es-para-iniciar-um-jo
> [Main group 20] - Requisito 1 finalizado

- src/App.js
- src/Pages/Game/index.js
- src/Pages/Initial/index.js
- src/actions/index.js
- src/reducer/login.js
https://trello.com/b/79pH1hyD/project-trivia
> [Group 32] Requisito 4

- src/actions/index.js
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/reducers/index.js
- src/reducers/trivia.js
> Requisito 5 começando

- src/components/Questions.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
> Req  5 e 6 👍🏻 

- package-lock.json
- package.json
- src/App.js
- src/Pages/GamePage.js
- src/Pages/Login.js
- src/Redux/Action/index.js
- src/Redux/Reducers/index.js
- src/Redux/Reducers/player.js
- src/Redux/Store/index.js
- src/Services/fetchAPI.js
> [ Grupo 27 ] Project Trivia React Redux

- src/components/Questions.css
- src/components/Questions.jsx
- src/pages/Game.jsx
Requisito 8 feito com cronometro e tempo para os usuários resolverem as questões.
> Req 8 rafael main group 25

- src/components/Questions.css
- src/components/Questions.jsx
Adicionado arquivo Question.css para fazer as classes necessárias
> :white_check_mark: Requisito 7 concluido VQV

- src/actions/index.js
- src/components/Questions.css
- src/components/Questions.jsx
> Req 10 rafael main group 25 👍🏻 

- src/Pages/Login.js
- src/Services/fetchAPI.js
> Main group 27 requisito 2

- src/App.js
- src/actions/index.js
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/reducers/index.js
- src/reducers/player.js
https://trello.com/c/81dYr8lr/4-prioridade-1-tela-de-jogo-trivia-4-crie-um-header-que-deve-conter-as-informa%C3%A7%C3%B5es-da-pessoa-jogadora
> [Main group 20] -  req 4

- src/App.js
- src/pages/Login.jsx
- src/pages/Settings.jsx
https://trello.com/c/RJ7G6vms/3-prioridade-1-tela-de-in%C3%ADcio-login-3-crie-um-bot%C3%A3o-que-leva-a-pessoa-para-a-tela-de-configura%C3%A7%C3%A3o
> [Main group 20] - Requisito 3

- src/App.js
- src/actions/index.js
- src/pages/Game.jsx
- src/reducers/game.js
https://trello.com/c/3mA27Qjx/5-prioridade-1-tela-de-jogo-trivia-5-crie-a-p%C3%A1gina-de-jogo-que-deve-conter-as-informa%C3%A7%C3%B5es-relacionadas-%C3%A0-pergunta
> [Main group 20] - Requisito 5

- src/components/BtnCorrect.js
- src/components/BtnWrong.js
- src/pages/GameScreen.js
> Main group 29 requisito 7

- package-lock.json
- package.json
- src/Components/Header/index.js
- src/pages/Login/index.js
- src/pages/Trivia/index.js
- src/redux/actions/index.js
- src/redux/reducers/apiReducer.js
> [Grupo 8 Joao França]Requisito 4

- README.md
- src/App.js
- src/index.js
- src/pages/Login.js
- src/reducers/userReducer.js
- src/store/index.js
> Requisito 1.

- src/components/Question.js
- src/pages/TriviaGame.js
- src/redux/actions/index.js
> {Group-14] Requisito 5, 6 finalizado

- src/App.css
- src/components/Question.js
- src/pages/TriviaGame.js
- src/redux/actions/index.js
> [Group 14] Requisito 7

- src/pages/Game.jsx
- src/pages/Login.jsx
- src/redux/actions/index.js
- src/redux/reducers/play.js
Desenvolve requisito 4 em dupla com Matteus Fernandes
> [GRUPO 22]Requisito 4

- src/App.css
- src/pages/TriviaGame.js
- src/redux/actions/index.js
> [Group 14] Requisito 7, 8

- src/Pages/Game/index.js
- src/Pages/Initial/index.js
- src/actions/index.js
- src/reducer/login.js
https://trello.com/b/79pH1hyD/project-trivia
> [Group 32] requisito 5

- src/Components/Game/index.js
- src/Components/Timmer/index.js
- src/helpers/scoreCalculator.js
- src/pages/Login/index.js
> Main group 8 joao franca requisito 6

- src/App.css
- src/pages/Game.jsx
- src/pages/Question.jsx
> [Grupo 5] - Requisito 7

- cypress/integration/project.spec.js
- src/components/Header.js
- src/pages/FeedBack.js
> Main group 29 ex12

- cypress/integration/project.spec.js
- src/App.js
- src/components/BtnCorrect.js
- src/components/BtnWrong.js
- src/components/Header.js
- src/components/NextQuestionBtn.js
- src/pages/FeedBack.js
- src/pages/GameScreen.js
> Main group 29 ex13

- cypress/integration/project.spec.js
- src/App.js
- src/components/BtnCorrect.js
- src/components/BtnWrong.js
- src/components/Header.js
- src/components/HeaderFback.js
- src/components/NextQuestionBtn.js
- src/components/Results.js
- src/pages/FeedBack.js
- src/pages/GameScreen.js
Nao confia nos outros PR, confia NESSE! eu tinha esquecido de tirar os .skip .only q eu coloquei nos testes. Esse PR esta passando nos testes ate o req14 =)
> Main group 29 ex14

- src/pages/Question.jsx
> [Grupo 5] Requisito 8

- cypress/integration/project.spec.js
- package-lock.json
- src/components/BtnRestart.js
- src/pages/FeedBack.js
> finalize req15

- src/components/Boolean.jsx
- src/components/Multiple.jsx
- src/pages/Game.jsx
Foram feitos ajustes para, quando escolhida a resposta, parar o cronometro.
Integração final entre requisito 7 e 8.
> Squad24 aleilton trivia requisito08 ajustes

- src/App.js
- src/components/Header.jsx
- src/pages/Feedback.jsx
- src/pages/Login.js
- src/pages/Ranking.js
- src/pages/TriviaGame.js
- src/redux/actions/index.js
- src/redux/reducers/player.js
> [Group 14] Requisito 9

- src/pages/Game.jsx
https://trello.com/c/JqY3FRyz/8-prioridade-3-tela-de-jogo-trivia-8-desenvolva-um-timer-onde-a-pessoa-que-joga-tem-30-segundos-para-responder
> [Grupo 20][Requisito 8]

- src/App.css
- src/pages/Game.jsx
> Main group 20 req 7

- src/components/FeedbackMensage.js
- src/components/Timer.js
- src/pages/PageGame.jsx
https://trello.com/c/XLdY6MyH/8-prioridade-3-tela-de-jogo-trivia-8-desenvolva-um-timer-onde-a-pessoa-que-joga-tem-30-segundos-para-responder
> [Group 11] Requirement 08

- src/actions/index.js
- src/pages/FeedBack.jsx
- src/pages/Game.jsx
https://trello.com/c/l4pkYjxG/10-prioridade-3-tela-de-jogo-trivia-10-crie-um-bot%C3%A3o-de-pr%C3%B3xima-que-apare%C3%A7a-ap%C3%B3s-a-resposta-ser-dada
> [Main group 20] - Req10

- src/actions/index.js
- src/pages/Feedback.jsx
- src/pages/Question.jsx
- src/reducers/playerReducer.js
> [Grupo 5] Requisito 13

- src/pages/Feedback.jsx
Requisitos 1 ao 15 passando no teste e lint ok, conflitos resolvidos.
> [GRUPO 1] - Requisitos 1 ao 15

- src/actions/index.js
- src/components/Header.js
- src/helpers/index.js
- src/pages/Game.jsx
Diminui quantidade de linhas página Game:
- criado components/Header.js;
- criado helpers/index.js (seta estado inicial de 'state' no localStorage);
> [Group-20] Fix Lint max-lines page Game

- src/components/Answers.jsx
- src/components/NextQuestionButton.jsx
- src/components/PlayButton.js
- src/pages/PageGame.jsx
https://trello.com/c/5t3TKhIV/10-prioridade-3-tela-de-jogo-trivia-10-crie-um-bot%C3%A3o-de-pr%C3%B3xima-que-apare%C3%A7a-ap%C3%B3s-a-resposta-ser-dada
Features implementadas:
1 - novo atributo no estado local "isRunning" para indicar quando o jogo está rodando ou parado.
2 - adição do botão Próxima para passar para a questão seguinte
2.1 - o botão "próxima" está sendo renderizado condicionalmente baseado no estado local isRunning.
2.2 - O botão próximo possui um "handler" que retira os style das bordas das questões, incrementa o atribut counter em uma unidade caso seja menor que número de questões e retorna o estado IsRunning para true;
3.3 - atualização do handler handleClick das questões, alterando o estado isRunning para falso, fazendo com que os botões não estejam mais "clicáveis"
> Main group 11 requirement 10

- src/pages/Feedback.jsx
- src/pages/Question.jsx
> [Grupo 5] Requisito 12

- README.md
- src/pages/Feedback.jsx
Requisito 15 finalizado :rocket:
> [GRUPO 5] Requisito 15

- src/App.js
- src/pages/Feedback.jsx
- src/pages/Ranking.jsx
> [GRUPO 5] Requisito 16

- cypress/integration/project.spec.js
- src/pages/FeedBack.jsx
- src/pages/Game.jsx
https://trello.com/c/mPcsU1iq/15-prioridade-3-tela-de-feedback-15-crie-a-op%C3%A7%C3%A3o-para-a-pessoa-jogadora-poder-jogar-novamente
> [Main group 20] - Req 15

- src/components/BtnPlayAgain.jsx
- src/components/FeedbackHeader.jsx
- src/components/FeedbackMsg.jsx
- src/components/Timer.jsx
- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/pages/Ranking.jsx
- src/redux/reducers/index.js
- src/redux/reducers/scores.js
- src/redux/reducers/timer.js
- src/redux/reducers/user.js
- src/redux/store/index.js
- src/services/getLocal.js
- src/services/saveToLocal.js
> [Group7] - Refatorando v3

- cypress/integration/project.spec.js
- src/pages/FeedBack.jsx
- src/pages/Game.jsx
- src/pages/Ranking.jsx
https://trello.com/c/WydesKJW/16-prioridade-3-tela-de-feedback-16-crie-a-op%C3%A7%C3%A3o-para-a-pessoa-jogadora-poder-visualizar-a-tela-de-ranking
> [Main group 20] - Req 16

- cypress/integration/project.spec.js
- src/pages/FeedBack.jsx
- src/pages/Ranking.jsx
https://trello.com/c/vK2G2fhV/18-prioridade-3-tela-de-ranking-18-crie-um-bot%C3%A3o-para-ir-ao-in%C3%ADcio
> [Main group 20] - Req 18

- src/App.js
- src/pages/Feedback.jsx
- src/pages/PageGame.jsx
https://trello.com/c/xEkDKzMb/11-prioridade-2-tela-de-jogo-trivia-11-desenvolva-o-jogo-de-forma-que-a-pessoa-que-joga-deve-responder-5-perguntas-no-total
> Main group 11 requirement 11

- src/App.js
- src/pages/Feedback/index.js
- src/pages/Ranking/index.js
> Main group 8 req16

- src/pages/Feedback.jsx
- src/pages/Ranking.jsx
> [GRUPO 5] Requisito 18

- src/components/PlayerResults.jsx
- src/pages/Feedback.jsx
Link Card Trello:
https://trello.com/c/huAdUeYa/14-prioridade-1-tela-de-feedback-14-exiba-as-informa%C3%A7%C3%B5es-relacionadas-aos-resultados-obtidos-para-a-pessoa-usu%C3%A1ria
> requirement 14 completed

- src/actions/index.js
- src/pages/FeedBack.jsx
- src/pages/Login.jsx
- src/pages/Ranking.jsx
- src/reducers/player.js
14) https://trello.com/c/Lbfkmf7U/14-prioridade-1-tela-de-feedback-14-exiba-as-informa%C3%A7%C3%B5es-relacionadas-aos-resultados-obtidos-para-a-pessoa-usu%C3%A1ria
17) https://trello.com/c/bqqr5wRZ/17-prioridade-1-tela-de-ranking-17-crie-a-tela-de-ranking
> [Main Group 20] - Requisitos 14 e 17

- src/pages/Feedback.jsx
https://trello.com/c/ZgsT9BqB/15-prioridade-3-tela-de-feedback-15-crie-a-op%C3%A7%C3%A3o-para-a-pessoa-jogadora-poder-jogar-novamente
> requirement 15 completed

- src/components/Answers.jsx
- src/components/GravatarHeader.jsx
- src/components/HomeButton.jsx
- src/components/PlayButton.js
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/pages/Ranking.jsx
- src/redux/actions/index.js
- src/redux/reducers/config.js
https://trello.com/c/mGgYFCmZ/23-prioridade-4-extra-reavaliar-o-c%C3%B3digo-para-cumprir-com-a-possibilidade-do-token-expirar
> [Group 11] Requirement 04 fix

- package-lock.json
- src/App.css
- src/components/Questions.jsx
- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/pages/Ranking.jsx
- src/pages/Settings.jsx
corrige clicar multiplas vezes na opcao correta e adiciona css medonho na pagina game
> corrige clicar multiplas vezes na opcao correta e adiciona css medonho na pagina game

- src/components/Question.js
- src/components/Timer.js
- src/pages/TriviaGame.js
- src/redux/actions/index.js
- src/services/index.js
Refatoração das funções e aleatoriedade das respostas
> [Group-14] Refatoração das funções e aleatoriedade das respostas

- cypress/integration/project.spec.js
- src/actions/index.js
- src/components/HeaderFeedback.js
- src/pages/feedback.js
- src/pages/ranking.js
- src/reducers/index.js
- src/reducers/player.js
- src/reducers/ranking.js
> Main group 3 requisito 17
